//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt_45
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Приход уход.
    /// </summary>
    // *** Start programmer edit section *** (ПриходУход CustomAttributes)

    // *** End programmer edit section *** (ПриходУход CustomAttributes)
    [AutoAltered()]
    [Caption("Приход уход")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПриходУходE", new string[] {
            "СправУч as \'Фио ученика\'",
            "СправУч.Фио as \'Фио ученика\'",
            "СправУч.КлассУч.Назв as \'Класс ученика\'",
            "СправУч.Номер.Наименование as \'Номер карты\'",
            "СправУч.СправРод.Фио as \'Фио родителя\'",
            "Расписание as \'Расписание уроков\'",
            "Расписание.Урок as \'Номер урока\'",
            "Расписание.ПериодОт as \'Период От\'",
            "Расписание.ПериодДо as \'Период До\'",
            "Статус as \'Статус\'",
            "ВрПриУх as \'Время прихода/ухода\'"})]
    [MasterViewDefineAttribute("ПриходУходE", "СправУч", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фио ученика")]
    [MasterViewDefineAttribute("ПриходУходE", "Расписание", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер урока")]
    [View("ПриходУходL", new string[] {
            "Статус as \'Статус\'",
            "СправУч.Фио as \'Фио ученика\'",
            "СправУч.КлассУч.Назв as \'Класс ученика\'",
            "СправУч.Номер.Наименование as \'Номер карты\'",
            "СправУч.СправРод.Фио as \'Фио родителя\'",
            "Расписание.Урок as \'Номер урока\'",
            "Расписание.ПериодОт as \'Период От\'",
            "Расписание.ПериодДо as \'Период До\'",
            "ВрПриУх as \'Время прихода/ухода\'"})]
    public class ПриходУход : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Proekt_45.Статус fСтатус;
        
        private string fВрПриУх;
        
        private IIS.Proekt_45.Расписание fРасписание;
        
        private IIS.Proekt_45.СправУч fСправУч;
        
        // *** Start programmer edit section *** (ПриходУход CustomMembers)

        // *** End programmer edit section *** (ПриходУход CustomMembers)

        
        /// <summary>
        /// ВрПриУх.
        /// </summary>
        // *** Start programmer edit section *** (ПриходУход.ВрПриУх CustomAttributes)

        // *** End programmer edit section *** (ПриходУход.ВрПриУх CustomAttributes)
        [StrLen(255)]
        public virtual string ВрПриУх
        {
            get
            {
                // *** Start programmer edit section *** (ПриходУход.ВрПриУх Get start)

                // *** End programmer edit section *** (ПриходУход.ВрПриУх Get start)
                string result = this.fВрПриУх;
                // *** Start programmer edit section *** (ПриходУход.ВрПриУх Get end)

                // *** End programmer edit section *** (ПриходУход.ВрПриУх Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходУход.ВрПриУх Set start)

                // *** End programmer edit section *** (ПриходУход.ВрПриУх Set start)
                this.fВрПриУх = value;
                // *** Start programmer edit section *** (ПриходУход.ВрПриУх Set end)

                // *** End programmer edit section *** (ПриходУход.ВрПриУх Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (ПриходУход.Статус CustomAttributes)

        // *** End programmer edit section *** (ПриходУход.Статус CustomAttributes)
        public virtual IIS.Proekt_45.Статус Статус
        {
            get
            {
                // *** Start programmer edit section *** (ПриходУход.Статус Get start)

                // *** End programmer edit section *** (ПриходУход.Статус Get start)
                IIS.Proekt_45.Статус result = this.fСтатус;
                // *** Start programmer edit section *** (ПриходУход.Статус Get end)

                // *** End programmer edit section *** (ПриходУход.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходУход.Статус Set start)

                // *** End programmer edit section *** (ПриходУход.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (ПриходУход.Статус Set end)

                // *** End programmer edit section *** (ПриходУход.Статус Set end)
            }
        }
        
        /// <summary>
        /// Приход уход.
        /// </summary>
        // *** Start programmer edit section *** (ПриходУход.Расписание CustomAttributes)

        // *** End programmer edit section *** (ПриходУход.Расписание CustomAttributes)
        [PropertyStorage(new string[] {
                "Расписание"})]
        [NotNull()]
        public virtual IIS.Proekt_45.Расписание Расписание
        {
            get
            {
                // *** Start programmer edit section *** (ПриходУход.Расписание Get start)

                // *** End programmer edit section *** (ПриходУход.Расписание Get start)
                IIS.Proekt_45.Расписание result = this.fРасписание;
                // *** Start programmer edit section *** (ПриходУход.Расписание Get end)

                // *** End programmer edit section *** (ПриходУход.Расписание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходУход.Расписание Set start)

                // *** End programmer edit section *** (ПриходУход.Расписание Set start)
                this.fРасписание = value;
                // *** Start programmer edit section *** (ПриходУход.Расписание Set end)

                // *** End programmer edit section *** (ПриходУход.Расписание Set end)
            }
        }
        
        /// <summary>
        /// Приход уход.
        /// </summary>
        // *** Start programmer edit section *** (ПриходУход.СправУч CustomAttributes)

        // *** End programmer edit section *** (ПриходУход.СправУч CustomAttributes)
        [PropertyStorage(new string[] {
                "СправУч"})]
        [NotNull()]
        public virtual IIS.Proekt_45.СправУч СправУч
        {
            get
            {
                // *** Start programmer edit section *** (ПриходУход.СправУч Get start)

                // *** End programmer edit section *** (ПриходУход.СправУч Get start)
                IIS.Proekt_45.СправУч result = this.fСправУч;
                // *** Start programmer edit section *** (ПриходУход.СправУч Get end)

                // *** End programmer edit section *** (ПриходУход.СправУч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходУход.СправУч Set start)

                // *** End programmer edit section *** (ПриходУход.СправУч Set start)
                this.fСправУч = value;
                // *** Start programmer edit section *** (ПриходУход.СправУч Set end)

                // *** End programmer edit section *** (ПриходУход.СправУч Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПриходУходE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриходУходE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриходУходE", typeof(IIS.Proekt_45.ПриходУход));
                }
            }
            
            /// <summary>
            /// "ПриходУходL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриходУходL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриходУходL", typeof(IIS.Proekt_45.ПриходУход));
                }
            }
        }
    }
}
